MODEL:
  META_ARCHITECTURE: "EntityFPN"
  MASK_ON: False
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
    FIX: false
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  WEIGHTS: "data/pretrained_model/ours_R50_3x.pth"
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    FIX: false
  FCOS:
    NUM_CLASSES: 1
  CONDINST:
    CLASS_AGNOSTIC: True
    TRAIN_MAX_PROPOSALS_PER_IMAGE: 120
    MASK_BRANCH:
      SEMANTIC_LOSS_ON: False
      IN_FEATURES: ["p3", "p4", "p5"]
    MASK_HEAD:
      CLUSTER_WEIGHT: 0.5
      DYNAMIC: ["111", "110", "101", "100", "011", "010", "001"]
      DYNAMIC_WEIGHT: [1.0, 1.0, 1.0, 1.0, 0.25, 0.25, 0.25]
DATASETS:
  TRAIN: ("3rscan_train_entity",)
  TEST: ("3rscan_val_entity",)
SOLVER:
  WARMUP_ITERS: 10000
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  STEPS: (150000, 240000)
  MAX_ITER: 300000
  CHECKPOINT_PERIOD: 10000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
TEST:
  CLASS_AGNOSTIC: True
