MODEL:
  META_ARCHITECTURE: "EntityFPN"
  MASK_ON: False
  BACKBONE:
    NAME: "build_retinanet_swin_fpn_backbone"
    FREEZE_AT: -1
    FIX: true
  SWINT:
    EMBED_DIM: 192
    PATCH_SIZE: 4
    OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
    DEPTHS: [2, 2, 18, 2]
    NUM_HEADS: [6, 12, 24, 48]
    WINDOW_SIZE: 7
    MLP_RATIO: 4
    DROP_PATH_RATE: 0.2
    APE: False
  WEIGHTS: "data/pretrained_model/swin_l7_3x.pth"
  FPN:
    IN_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
    TOP_LEVELS: 2
  FCOS:
    NUM_CLASSES: 1
  CONDINST:
    CLASS_AGNOSTIC: True
    TRAIN_MAX_PROPOSALS_PER_IMAGE: 120
    MASK_BRANCH:
      SEMANTIC_LOSS_ON: False
      IN_FEATURES: ["p3", "p4", "p5"]
    MASK_HEAD:
      CLUSTER_WEIGHT: 0.5
      DYNAMIC: ["111", "110", "101", "100", "011", "010", "001"]
      DYNAMIC_WEIGHT: [1.0, 1.0, 1.0, 1.0, 0.25, 0.25, 0.25]
DATASETS:
  TRAIN: ("3rscan_train_entity",)
  TEST: ("3rscan_val_entity",)
SOLVER:
  OPTIMIZER: "adamw"
  WARMUP_ITERS: 10000
  WEIGHT_DECAY: 0.05
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  STEPS: (50000, 80000)
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 10000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
TEST:
  CLASS_AGNOSTIC: True
